import type { TablesSchema } from "tinybase"

const text = { type: "string", default: "" } as const
const amount = { type: "number", default: 0 } as const

export const TABLES = {
  products: "products",
  menuCategories: "menuCategories",
  recipeLines: "recipeLines",
  outletSettings: "outletSettings",
  staffMembers: "staffMembers",
  staffMemberRoles: "staffMemberRoles",
  staffPreferredSlots: "staffPreferredSlots",
  staffDefaultDaysOff: "staffDefaultDaysOff",
  shiftTemplates: "shiftTemplates",
  shiftRoleRequirements: "shiftRoleRequirements",
  shiftAssignments: "shiftAssignments",
  attendanceEvents: "attendanceEvents",
  weekPreferences: "weekPreferences",
  weekPreferenceSlots: "weekPreferenceSlots",
  dayOffSuggestions: "dayOffSuggestions",
  scheduledDaysOff: "scheduledDaysOff",
  inventoryItems: "inventoryItems",
  inventoryLots: "inventoryLots",
  inventoryStockMovements: "inventoryStockMovements",
  recipes: "recipes",
  recipeIngredients: "recipeIngredients",
  kitchenOrders: "kitchenOrders",
  kitchenOrderItems: "kitchenOrderItems",
  orders: "orders",
  orderItems: "orderItems",
  payments: "payments",
} as const

export type TableName = (typeof TABLES)[keyof typeof TABLES]

export const tablesSchema = {
  products: {
    name: text,
    sku: text,
    price: amount,
    stock: amount,
    kind: { type: "string", default: "menu" },
    category: text,
    unit: text,
    note: text,
    isActive: { type: "boolean", default: true },
    lowStock: amount,
    createdAt: amount,
    updatedAt: amount,
  },
  menuCategories: {
    slug: text,
    name: text,
    sortOrder: amount,
    createdAt: amount,
    updatedAt: amount,
  },
  recipeLines: {
    productId: text,
    ingredientId: text,
    qty: amount,
    createdAt: amount,
  },
  outletSettings: {
    outletId: text,
    openMinutes: amount,
    closeMinutes: amount,
    weekStartsOn: { type: "number", default: 1 },
    preferenceDeadlineWeekday: { type: "number", default: 3 },
    preferenceDeadlineMinutes: amount,
    maxConsecutiveWorkDays: { type: "number", default: 6 },
    targetDaysOffPerWeek: { type: "number", default: 1 },
    targetHoursPerWeek: amount,
    hoursSkewPercent: { type: "number", default: 25 },
    weekendFairnessEnabled: { type: "boolean", default: true },
    graceLateMinutes: { type: "number", default: 10 },
    createdAt: amount,
    updatedAt: amount,
  },
  staffMembers: {
    name: text,
    nickname: text,
    pinHash: text,
    pinSalt: text,
    isActive: { type: "boolean", default: true },
    includeInAttendance: { type: "boolean", default: true },
    deletedAt: amount,
    outletId: text,
    createdAt: amount,
    updatedAt: amount,
  },
  staffMemberRoles: {
    staffId: text,
    role: text,
    createdAt: amount,
  },
  staffPreferredSlots: {
    staffId: text,
    templateId: text,
    rank: amount,
  },
  staffDefaultDaysOff: {
    staffId: text,
    weekday: amount,
  },
  shiftTemplates: {
    name: text,
    startMinutes: amount,
    endMinutes: amount,
    sortOrder: amount,
    minStaffCount: { type: "number", default: 1 },
    isActive: { type: "boolean", default: true },
    outletId: text,
    createdAt: amount,
    updatedAt: amount,
  },
  shiftRoleRequirements: {
    templateId: text,
    role: text,
    minCount: amount,
    createdAt: amount,
  },
  shiftAssignments: {
    staffId: text,
    templateId: text,
    workDate: text,
    startMinutes: amount,
    endMinutes: amount,
    dutyRole: text,
    status: text,
    outletId: text,
    note: text,
    actorStaffId: text,
    createdAt: amount,
    updatedAt: amount,
  },
  attendanceEvents: {
    staffId: text,
    type: text,
    occurredAt: amount,
    recordedAt: amount,
    deviceId: text,
    shiftAssignmentId: text,
    outletId: text,
    note: text,
    actorStaffId: text,
    correctsEventId: text,
  },
  weekPreferences: {
    staffId: text,
    weekStart: text,
    note: text,
    status: text,
    submittedAt: amount,
    createdAt: amount,
    updatedAt: amount,
  },
  weekPreferenceSlots: {
    preferenceId: text,
    templateId: text,
    rank: amount,
  },
  dayOffSuggestions: {
    staffId: text,
    weekStart: text,
    workDate: text,
    rank: amount,
    note: text,
    status: text,
    alternativeDate: text,
    actorStaffId: text,
    createdAt: amount,
    updatedAt: amount,
  },
  scheduledDaysOff: {
    staffId: text,
    workDate: text,
    weekStart: text,
    source: text,
    note: text,
    actorStaffId: text,
    createdAt: amount,
  },
  inventoryItems: {
    name: text,
    sku: text,
    baseUnit: text,
    minimumStock: amount,
    isActive: { type: "boolean", default: true },
    createdAt: amount,
    updatedAt: amount,
  },
  inventoryLots: {
    inventoryItemId: text,
    lotCode: text,
    receivedQuantity: amount,
    remainingQuantity: amount,
    baseUnit: text,
    receivedAt: text,
    expiryDate: text,
    containerCode: text,
    notes: text,
    createdAt: amount,
    updatedAt: amount,
  },
  inventoryStockMovements: {
    inventoryItemId: text,
    inventoryLotId: text,
    lotCode: text,
    containerCode: text,
    movementType: text,
    quantity: amount,
    unit: text,
    referenceType: text,
    referenceId: text,
    orderId: text,
    menuProductId: text,
    kitchenOrderItemId: text,
    reason: text,
    actorStaffId: text,
    createdAt: amount,
  },
  recipes: {
    menuProductId: text,
    version: { type: "number", default: 1 },
    isActive: { type: "boolean", default: true },
    createdAt: amount,
    updatedAt: amount,
  },
  recipeIngredients: {
    recipeId: text,
    inventoryItemId: text,
    quantity: amount,
    unit: text,
    sortOrder: amount,
    createdAt: amount,
    updatedAt: amount,
  },
  kitchenOrders: {
    sourceOrderId: text,
    orderNumber: text,
    customerName: text,
    status: { type: "string", default: "queued" },
    placedAt: amount,
    createdAt: amount,
    updatedAt: amount,
  },
  kitchenOrderItems: {
    orderId: text,
    sourceOrderItemId: text,
    menuProductId: text,
    menuName: text,
    quantity: amount,
    status: { type: "string", default: "queued" },
    startedAt: amount,
    sortOrder: amount,
    createdAt: amount,
    updatedAt: amount,
  },
  orders: {
    orderNumber: text,
    status: { type: "string", default: "OPEN" },
    subtotal: amount,
    total: amount,
    createdAt: amount,
    updatedAt: amount,
  },
  orderItems: {
    orderId: text,
    menuProductId: text,
    name: text,
    quantity: amount,
    price: amount,
    subtotal: amount,
    sortOrder: amount,
    createdAt: amount,
  },
  payments: {
    orderId: text,
    method: { type: "string", default: "CASH" },
    amount: amount,
    change: amount,
    actorStaffId: text,
    paidAt: amount,
    createdAt: amount,
  },
} as const satisfies TablesSchema
